### ISSUE TITLE
Add GDPR options for compliance?

### ISSUE THREAD

**Issue by skidvis** [dillpixel/fitbit-google-analytics#2]
Allow setting the anonymizeIp setting to true, etc.

**Comment by daveyjones** [comment]
Great idea—I'll look into that.

**Comment by daveyjones** [comment]
Just a note to myself: the docs for the Anonymize IP parameter are here:

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#aip

Note: even though JavaScript uses camel case, I prefer snake case because we can avoid issues like:

- Is that a lowercase "L" or an uppercase "i"?
- Should I capitalize all the letters in an acronym (like IP) or just the first letter?

So I'll probably call the option `anonymize_ip`.

**Comment by daveyjones** [comment]
This feature has been added! 87a6d982dd2ccb2328a8bc41ca300a6a720d596b

**Comment by daveyjones** [comment]
I should also mention that I decided to set the default to `1`. It seemed like a good idea to anonymize the IP by default and allow users to disable that if needed.
